project:
  type: book
  output-dir: docs

book:
  title: "Ellaine Juvina"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224071 Ellaine Juvina"
  date: "10/18/2025"
  chapters:
    - part: "🎭 Bagian Personal"
      chapters:
        - index.qmd
        - intro.qmd
        - My_Song_for_You/index.qmd
        - My_Stories_for_You/index.qmd

    - part: "📊 Bagian Analitis"
      chapters:
        - My_Shapes/index.qmd
        - My_Personal_Reviews/index.qmd
        - My_Concepts/index.qmd

    - part: "💼 Bagian Profesional"
      chapters:
        - My_Opinions/index.qmd
        - My_Innovations/index.qmd
        - My_Knowledge/index.qmd
        - My_Professional_Reviews/index.qmd

    - part: "📖 Penutup"
      chapters:
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
