project:
  type: website
  output-dir: docs

website:
  title: "Ellaine Juvina Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction

format:
  html:
    theme: cosmo
