project:
  type: book
  output-dir: docs

book:
  title: "Ellaine Juvina"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224071 Ellaine Juvina"
  date: "10/18/2025"
  chapters:
    - part: "🎭 Bagian Personal"
      chapters:
        - file: index.qmd
          title: "Gerbang Aucloire"
        - file: intro.qmd
          title: "Perkenalan Diri" 
        - file: My_Song_for_You/index.qmd
          title: "Lagu untuk Anda"
        - file: My_Stories_for_You/index.qmd
          title: "Cerita untuk Anda"

    - part: "📊 Bagian Analitis"
      chapters:
        - file: My_Shapes/index.qmd
          title: "Bentuk dan Pola"
        - file: My_Personal_Reviews/index.qmd
          title: "Review Personal"
        - file: My_Concepts/index.qmd
          title: "Konsep Pemikiran"

    - part: "💼 Bagian Profesional" 
      chapters:
        - file: My_Opinions/index.qmd
          title: "Opini dan Pandangan"
        - file: My_Innovations/index.qmd
          title: "Inovasi"
        - file: My_Knowledge/index.qmd
          title: "Pengetahuan"
        - file: My_Professional_Reviews/index.qmd
          title: "Review Profesional"

    - part: "📖 Penutup"
      chapters:
        - file: summary.qmd
          title: "Ringkasan"
        - file: references.qmd
          title: "Referensi"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
